### ISSUE TITLE
Don't support space char in base path

### ISSUE THREAD

**Issue by ewoody** [softlayer/ember-cli-jsdoc#16]
Reproduce Steps:
1. Windows, project path is "c:\my doc\my project"
2. run "ember ember-cli-jsdoc" in this project path
3. See error "c:\my" is not a command

Suggested fix - 

Line 11, in ember-cli-jsdoc.js, change to

cmd = '\"' + cmd + '\"' + ' -c jsdoc.json';

then it works on Windows

**Comment by notmessenger** [comment]
@SpikedKira Do you mind taking a look at this, as you've made some changes to this file in the past as well as you have a Windows environment to test it in?
