### ISSUE TITLE
Update the link to "Underscore Template library"

### ISSUE THREAD

**Issue by juwara0** [softlayer/ember-cli-jsdoc#28]
The link to the "Underscore Template library" at: https://github.com/softlayer/ember-cli-jsdoc/blob/0597aa2ac046d25cd8a5cf35e7747266ce28ea35/jsdocTemplates/default/README.md needs to be updated.

**Comment by notmessenger** [comment]
It is also broken on https://github.com/jsdoc3/jsdoc/tree/master/templates/default, which is where this content came/comes from
