### ISSUE TITLE
Path to jsdoc binary is incorrect for node 4.x and npm 2.x

### ISSUE THREAD

**Issue by sohara** [softlayer/ember-cli-jsdoc#36]
[This switch](https://github.com/softlayer/ember-cli-jsdoc/blob/master/lib/commands/ember-cli-jsdoc.js#L11) on the node process version to derive the path for the jsdoc binary produces an incorrect result in at least some cases. In our project that uses node 4.x and npm 2.x the correct path is `node_modules/.bin/jsdoc`.

**Comment by notmessenger** [comment]
This has been addressed by https://github.com/softlayer/ember-cli-jsdoc/commit/7ccca5207641447497ccf544f99e561186c7520b and released in [v1.6.0](https://github.com/softlayer/ember-cli-jsdoc/releases/tag/v1.6.0)
