### ISSUE TITLE
Question, How do you work with experimental babel features?

### ISSUE THREAD

**Issue by AKST** [softlayer/ember-cli-jsdoc#39]
Hey I'm just wondering how this project deals with experimental babel features, such as decorators? Do you have a recommended approach? (apologise if this enquiry is kind of vague)

**Comment by notmessenger** [comment]
@AKST `v2.0.0` of this package was just released which upgraded `jsdoc` to `3.5.5` (https://github.com/jsdoc3/jsdoc/blob/master/CHANGES.md#350-july-2017) which means that the Babel compiler is being used and a lot of new features are supported, including decorators.

This issue - https://github.com/jsdoc3/jsdoc/issues/1165 - provides guidance on when encountering the `Stage 2 decorators may only be used with a class or a class method` error using some types of decorators.

**Comment by AKST** [comment]
Thanks for the update :) (Apologises for the slow reply)
