### ISSUE TITLE
Unable to parse async functions

### ISSUE THREAD

**Issue by erikmellum** [softlayer/ember-cli-jsdoc#40]
Throws `ERROR: Unable to parse` on async functions. I'll take a look and see if it's something I can take care of.

**Comment by Frozenfire92** [comment]
+1

**Comment by jdk0517** [comment]
I'm having the same issue with `ember-cli@2.18.0` and `ember-cli-jsdoc@1.6.0`

**Comment by notmessenger** [comment]
I have not yet looked into this yet but unfortunately it does not surprise me.  Just like `@whatever` are not able to be parsed I suspect this is the same thing.  Perhaps we will be able to find a work around but I know when I tried to support annotations it was a non-starter.

**Comment by jdk0517** [comment]
@erikmellum @notmessenger  it looks like bumping the jsdoc version to 3.5.0+ fixes this, as that is when it started supporting async: http://usejsdoc.org/tags-async.html. The current release of `ember-cli-jsdoc` uses `jsdoc@3.4.3`.

As a workaround for now, after installing `ember-cli-jsdoc` in my project as a dependency I am also installing `jsdoc@3.5.5`  - this seems to resolve the issue, and I can compile documentation from code which includes async functions using the `ember ember-cli-jsdoc` command.

When I have a sec I'll confirm that updating the dependency in `ember-cli-jsdoc` directly will have the same effect, and throw out a quick PR if so.

**Comment by notmessenger** [comment]
I am closing this issue as PR #42 resolved this issue and was released as `v2.0.0`

I closed your PR @jdk0517 in favor of #42 because it was not a completely accurate change-set for how this package is released. Thank you very much though for your research into this and the PR - I only made tweaks :-)
