### ISSUE TITLE
Supplied install command not working

### ISSUE THREAD

**Issue by NathanJang** [softlayer/ember-cli-jsdoc#7]
`ember install ember-cli-jsdoc` gets me `Install failed. Could not find addon with name: ember-cli-jsdoc`. I had to install it with `npm install ember-cli-jsdoc`.

**Comment by notmessenger** [comment]
That's strange.  Unfortunately I was not able to recreate this problem just now when attempting a brand new install in a brand new application but I will keep this issue open for a while in case anyone else experiences this problem as well.
